version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgesql/data